import { createContext, useContext, useState } from "react";

export const translations = {
  ro: {
    nav_automations: "Automatizări",
    nav_services: "Servicii",
    services_btn: "Ce Automatizăm Pentru Tine",
    nav_how: "Cum funcționează",
    nav_about: "Despre noi",
    nav_contact: "Contact",
    hero_sub: "AUTOMATIZĂRI AI.",
    hero_desc: "Scapă de munca repetitivă. Răspundem automat la emailuri, mesaje, programări și multe altele — cu AI, în locul tău.",
    hero_cta1: "Cere consultație gratuită",
    hero_cta2: "Vezi cum funcționează",
    hero_tag1: "⚡ Implementare în 7 zile garantat",
    hero_tag2: "🤖 Răspunsuri AI 24/7",
    hero_tag3: "🔒 Fără costuri ascunse",
    benefits_title: "Tot ce ai nevoie pentru a",
    benefits_title2: "automatiza afacerea ta",
    b1_title: "Răspunsuri automate la mesaje",
    b1_desc: "AI-ul nostru răspunde instant la emailuri, WhatsApp și DM-uri — fără să ridici un deget.",
    b2_title: "Programări gestionate automat",
    b2_desc: "Clienții se programează singuri, primesc confirmări și reminder-uri — totul fără intervenție umană.",
    b3_title: "Economisești zeci de ore pe lună",
    b3_desc: "Angajații tăi se ocupă de ce contează, nu de sarcini repetitive care pot fi automatizate.",
    b4_title: "Disponibil 24/7, fără pauze",
    b4_desc: "Automatizările funcționează non-stop. Clienții primesc răspuns chiar și noaptea sau în weekend.",
    b5_title: "Integrare rapidă și simplă",
    b5_desc: "Nu trebuie să schimbi nimic în business-ul tău. Noi integrăm AI-ul în uneltele pe care le folosești deja.",
    b6_title: "Rezultate măsurabile imediat",
    b6_desc: "Vezi în timp real câte mesaje, programări și lead-uri sunt gestionate automat pentru tine.",
    services_title: "Ce automatizăm",
    services_title2: "pentru tine?",
    services_sub: "Indiferent de tipul afacerii tale, avem automatizarea potrivită.",
    s1_tag: "Comunicare", s1_title: "Răspunsuri automate AI",
    s1_desc: "Un asistent AI care răspunde la emailuri, mesaje WhatsApp, Instagram DM și alte canale — instant, 24/7.",
    s1_f1: "Răspunsuri la emailuri automate", s1_f2: "WhatsApp & Instagram DM", s1_f3: "Ton personalizat pe brand", s1_f4: "Escaladare inteligentă la om",
    s2_tag: "Programări", s2_title: "Gestionare automată programări",
    s2_desc: "Clienții se programează online, primesc confirmări automate, reminder-uri și reprogramări — fără niciun efort.",
    s2_f1: "Calendar integrat automat", s2_f2: "Confirmări și reminder-uri SMS/email", s2_f3: "Reprogramări fără intervenție", s2_f4: "Sincronizare Google Calendar",
    s3_tag: "Lead-uri", s3_title: "Captare & nurturing lead-uri",
    s3_desc: "AI-ul identifică potențialii clienți, le răspunde imediat și îi ghidează printr-un funnel automatizat.",
    s3_f1: "Răspuns instant la lead-uri noi", s3_f2: "Follow-up automatizat", s3_f3: "Calificarea lead-urilor cu AI", s3_f4: "Integrare CRM",
    services_cta: "Cere ofertă",
    sv1_title: "Calificare & prospectare lead-uri cu AI",
    sv2_title: "Chatbot AI pentru suport clienți",
    sv3_title: "Pipeline de conținut pentru social media",
    sv4_title: "Procesare facturi & documente",
    sv5_title: "Îmbogățire & sincronizare date CRM",
    sv6_title: "Automatizare programări & rezervări",
    sv7_title: "Raportare & analiză cu AI",
    sv8_title: "Monitorizare & răspuns la recenzii",
    sv9_title: "Operațiuni comenzi & stocuri e-commerce",
    sv10_title: "Workflow onboarding angajați",
    sv11_title: "Automatizare personalizată",
    how_title: "3 pași simpli până la",
    how_title2: "business-ul tău automatizat",
    how_sub: "Procesul nostru e simplu și transparent. Tu ești informat la fiecare pas.",
    step1_title: "Ne contactezi", step1_desc: "Trimiți un mesaj sau completezi formularul. Analizăm gratuit procesele repetitive din business-ul tău.",
    step2_title: "Proiectăm automatizarea", step2_desc: "Construim fluxurile AI personalizate pentru nevoile tale — integrăm cu uneltele pe care le folosești deja.",
    step3_title: "AI lucrează pentru tine", step3_desc: "În 7 zile, automatizările sunt live. Clienții primesc răspuns instant, tu te ocupi de ce contează.",
    how_cta: "Începe acum — consultație gratuită",
    trust_title: "Automatizăm business-uri care vor să",
    trust_title2: "crească fără să muncească mai mult",
    trust_p1: "Valaro s-a născut dintr-o problemă reală:",
    trust_p1b: "antreprenorii pierd ore întregi în fiecare zi",
    trust_p1c: "răspunzând la aceleași mesaje, gestionând programări și urmărind lead-uri.",
    trust_p2: "Noi construim sisteme AI care fac asta automat — rapid, profesional și fără erori. Clienții tăi primesc răspuns instant,",
    trust_p2b: "iar tu îți recâștigi timpul.",
    trust_p3: "Nu vindem tehnologie complicată. Vindem timp, eficiență și liniște sufletească.",
    tc1_title: "Fără cunoștințe tehnice necesare", tc1_desc: "Noi ne ocupăm de tot, tu doar verifici rezultatele.",
    tc2_title: "Integrare cu uneltele tale", tc2_desc: "Gmail, WhatsApp, Calendly, CRM — conectăm tot.",
    tc3_title: "AI care vorbește ca tine", tc3_desc: "Răspunsurile sunt personalizate pe tonul brandului tău.",
    tc4_title: "Suport după implementare", tc4_desc: "Nu dispărem. Optimizăm constant pentru tine.",
    contact_tagline: "Lasă automatizarea\nsă lucreze pentru tine",
    contact_whatsapp: "WhatsApp",
    footer_rights: "Toate drepturile rezervate.",
    footer_privacy: "Politică de confidențialitate",
    footer_terms: "Termeni și condiții",
    cp_title: "Hai să automatizăm",
    cp_title2: "business-ul tău",
    cp_note: "Apăsând butonul, vei fi redirecționat către WhatsApp cu mesajul completat.",
    cp_back_label: "Înapoi",
    cp_inquiry_type: "Tip de cerere",
    cp_select: "Selectează o opțiune",
    cp_about: "Despre tine",
    cp_firstname: "Prenume",
    cp_lastname: "Nume",
    cp_email: "Adresă email",
    cp_phone: "Telefon",
    cp_business: "Business",
    cp_message: "Mesaj",
    cp_submit: "Trimite pe WhatsApp",
  },
  en: {
    nav_automations: "Automations",
    nav_services: "Services",
    services_btn: "What We Automate For You",
    nav_how: "How it works",
    nav_about: "About us",
    nav_contact: "Contact",
    hero_sub: "AI AUTOMATIONS.",
    hero_desc: "Eliminate repetitive work. We automatically reply to emails, messages, appointments and more — with AI, on your behalf.",
    hero_cta1: "Get free consultation",
    hero_cta2: "See how it works",
    hero_tag1: "⚡ Deployed in 7 days guaranteed",
    hero_tag2: "🤖 AI responses 24/7",
    hero_tag3: "🔒 No hidden costs",
    benefits_title: "Everything you need to",
    benefits_title2: "automate your business",
    b1_title: "Automatic message replies",
    b1_desc: "Our AI instantly replies to emails, WhatsApp and DMs — without you lifting a finger.",
    b2_title: "Automated appointment management",
    b2_desc: "Clients book themselves, receive confirmations and reminders — all without human intervention.",
    b3_title: "Save dozens of hours per month",
    b3_desc: "Your team focuses on what matters, not repetitive tasks that can be automated.",
    b4_title: "Available 24/7, no breaks",
    b4_desc: "Automations run non-stop. Clients get a reply even at night or on weekends.",
    b5_title: "Fast and simple integration",
    b5_desc: "No need to change anything in your business. We integrate AI into the tools you already use.",
    b6_title: "Measurable results immediately",
    b6_desc: "See in real time how many messages, appointments and leads are handled automatically for you.",
    services_title: "What do we automate",
    services_title2: "for you?",
    services_sub: "Whatever type of business you run, we have the right automation.",
    s1_tag: "Communication", s1_title: "Automatic AI replies",
    s1_desc: "An AI assistant that replies to emails, WhatsApp messages, Instagram DMs and other channels — instant, 24/7.",
    s1_f1: "Automatic email replies", s1_f2: "WhatsApp & Instagram DM", s1_f3: "Brand-personalized tone", s1_f4: "Intelligent escalation to human",
    s2_tag: "Appointments", s2_title: "Automatic appointment management",
    s2_desc: "Clients book online, receive automatic confirmations, reminders and rescheduling — with no effort from you.",
    s2_f1: "Automatically integrated calendar", s2_f2: "SMS/email confirmations & reminders", s2_f3: "Rescheduling without intervention", s2_f4: "Google Calendar sync",
    s3_tag: "Leads", s3_title: "Lead capture & nurturing",
    s3_desc: "AI identifies potential clients, replies immediately and guides them through an automated funnel to conversion.",
    s3_f1: "Instant reply to new leads", s3_f2: "Automated follow-up", s3_f3: "AI lead qualification", s3_f4: "CRM integration",
    services_cta: "Request offer",
    sv1_title: "AI lead qualification & outreach",
    sv2_title: "AI customer support chatbot",
    sv3_title: "Social media content pipeline",
    sv4_title: "Invoice & document processing",
    sv5_title: "CRM data enrichment & sync",
    sv6_title: "Appointment & booking automation",
    sv7_title: "AI-powered reporting & analytics",
    sv8_title: "Review monitoring & response",
    sv9_title: "E-commerce order & inventory ops",
    sv10_title: "Employee onboarding workflow",
    sv11_title: "Custom automation",
    how_title: "3 simple steps to",
    how_title2: "your automated business",
    how_sub: "Our process is simple and transparent. You are informed at every step.",
    step1_title: "Contact us", step1_desc: "Send a message or fill out the form. We analyse your repetitive processes for free.",
    step2_title: "We design the automation", step2_desc: "We build AI workflows customised to your needs — integrated with the tools you already use.",
    step3_title: "AI works for you", step3_desc: "In 7 days, automations are live. Clients get instant replies, you focus on what truly matters.",
    how_cta: "Start now — free consultation",
    trust_title: "We automate businesses that want to",
    trust_title2: "grow without working more",
    trust_p1: "Valaro was born from a real problem:",
    trust_p1b: "entrepreneurs lose hours every day",
    trust_p1c: "replying to the same messages, managing appointments and chasing leads.",
    trust_p2: "We build AI systems that do this automatically — fast, professional and error-free. Your clients get an instant reply,",
    trust_p2b: "and you get your time back.",
    trust_p3: "We don't sell complicated technology. We sell time, efficiency and peace of mind.",
    tc1_title: "No technical knowledge needed", tc1_desc: "We handle everything, you just check the results.",
    tc2_title: "Integration with your tools", tc2_desc: "Gmail, WhatsApp, Calendly, CRM — we connect everything.",
    tc3_title: "AI that speaks like you", tc3_desc: "Replies are personalised to your brand's tone.",
    tc4_title: "Support after deployment", tc4_desc: "We don't disappear. We continuously optimise for you.",
    contact_tagline: "Let automation\nwork for you",
    contact_whatsapp: "WhatsApp",
    footer_rights: "All rights reserved.",
    footer_privacy: "Privacy Policy",
    footer_terms: "Terms & Conditions",
    cp_title: "Let's automate",
    cp_title2: "your business",
    cp_note: "By pressing the button, you will be redirected to WhatsApp with the completed message.",
    cp_back_label: "Back",
    cp_inquiry_type: "Type of inquiry",
    cp_select: "Select an option",
    cp_about: "About you",
    cp_firstname: "First name",
    cp_lastname: "Last name",
    cp_email: "Email",
    cp_phone: "Phone",
    cp_business: "Business type",
    cp_message: "What do you want to automate?",
    cp_submit: "Send via WhatsApp",
  },
  de: {
    nav_automations: "Automatisierungen",
    nav_services: "Leistungen",
    services_btn: "Was Wir Für Sie Automatisieren",
    nav_how: "So funktioniert's",
    nav_about: "Über uns",
    nav_contact: "Kontakt",
    hero_sub: "KI-AUTOMATISIERUNGEN.",
    hero_desc: "Schluss mit Routinearbeit. Wir antworten automatisch auf E-Mails, Nachrichten, Termine und mehr — mit KI, in Ihrem Namen.",
    hero_cta1: "Kostenlose Beratung anfragen",
    hero_cta2: "So funktioniert's",
    hero_tag1: "⚡ Umsetzung in 7 Tagen garantiert",
    hero_tag2: "🤖 KI-Antworten 24/7",
    hero_tag3: "🔒 Keine versteckten Kosten",
    benefits_title: "Alles, was Sie brauchen, um",
    benefits_title2: "Ihr Unternehmen zu automatisieren",
    b1_title: "Automatische Nachrichtenantworten",
    b1_desc: "Unsere KI antwortet sofort auf E-Mails, WhatsApp und DMs — ohne dass Sie einen Finger rühren müssen.",
    b2_title: "Automatisches Terminmanagement",
    b2_desc: "Kunden buchen selbst, erhalten Bestätigungen und Erinnerungen — alles ohne menschliches Eingreifen.",
    b3_title: "Sparen Sie Dutzende Stunden pro Monat",
    b3_desc: "Ihr Team konzentriert sich auf das Wesentliche, nicht auf repetitive Aufgaben.",
    b4_title: "Rund um die Uhr verfügbar",
    b4_desc: "Automatisierungen laufen nonstop. Kunden erhalten auch nachts oder am Wochenende eine Antwort.",
    b5_title: "Schnelle und einfache Integration",
    b5_desc: "Sie müssen nichts in Ihrem Unternehmen ändern. Wir integrieren KI in die Tools, die Sie bereits nutzen.",
    b6_title: "Sofort messbare Ergebnisse",
    b6_desc: "Sehen Sie in Echtzeit, wie viele Nachrichten, Termine und Leads automatisch bearbeitet werden.",
    services_title: "Was automatisieren wir",
    services_title2: "für Sie?",
    services_sub: "Egal welche Art von Unternehmen Sie führen, wir haben die passende Automatisierung.",
    s1_tag: "Kommunikation", s1_title: "Automatische KI-Antworten",
    s1_desc: "Ein KI-Assistent, der auf E-Mails, WhatsApp-Nachrichten, Instagram-DMs antwortet — sofort, 24/7.",
    s1_f1: "Automatische E-Mail-Antworten", s1_f2: "WhatsApp & Instagram DM", s1_f3: "Markenpersonalisierter Ton", s1_f4: "Intelligente Weiterleitung",
    s2_tag: "Termine", s2_title: "Automatisches Terminmanagement",
    s2_desc: "Kunden buchen online, erhalten automatische Bestätigungen, Erinnerungen und Umbuchungen.",
    s2_f1: "Automatisch integrierter Kalender", s2_f2: "SMS/E-Mail-Bestätigungen", s2_f3: "Umbuchung ohne Eingriff", s2_f4: "Google Calendar-Synchronisierung",
    s3_tag: "Leads", s3_title: "Lead-Erfassung & -Nurturing",
    s3_desc: "KI identifiziert potenzielle Kunden, antwortet sofort und führt sie durch einen automatisierten Funnel.",
    s3_f1: "Sofortantwort auf neue Leads", s3_f2: "Automatisiertes Follow-up", s3_f3: "KI-Lead-Qualifizierung", s3_f4: "CRM-Integration",
    services_cta: "Angebot anfragen",
    sv1_title: "KI-Lead-Qualifizierung & Outreach",
    sv2_title: "KI-Kundensupport-Chatbot",
    sv3_title: "Social-Media-Content-Pipeline",
    sv4_title: "Rechnungs- & Dokumentenverarbeitung",
    sv5_title: "CRM-Datenanreicherung & -Synchronisierung",
    sv6_title: "Termin- & Buchungsautomatisierung",
    sv7_title: "KI-gestützte Berichterstattung",
    sv8_title: "Bewertungsüberwachung & -beantwortung",
    sv9_title: "E-Commerce-Bestell- & Lagerverwaltung",
    sv10_title: "Mitarbeiter-Onboarding-Workflow",
    sv11_title: "Individuelle Automatisierung",
    how_title: "3 einfache Schritte zu",
    how_title2: "Ihrem automatisierten Unternehmen",
    how_sub: "Unser Prozess ist einfach und transparent. Sie werden bei jedem Schritt informiert.",
    step1_title: "Kontakt aufnehmen", step1_desc: "Schicken Sie eine Nachricht oder füllen Sie das Formular aus. Wir analysieren kostenlos.",
    step2_title: "Wir entwerfen die Automatisierung", step2_desc: "Wir bauen KI-Workflows, die auf Ihre Bedürfnisse zugeschnitten sind.",
    step3_title: "KI arbeitet für Sie", step3_desc: "In 7 Tagen sind die Automatisierungen live. Kunden erhalten sofortige Antworten.",
    how_cta: "Jetzt starten — kostenlose Beratung",
    trust_title: "Wir automatisieren Unternehmen, die",
    trust_title2: "wachsen wollen, ohne mehr zu arbeiten",
    trust_p1: "Valaro entstand aus einem echten Problem:",
    trust_p1b: "Unternehmer verlieren täglich Stunden",
    trust_p1c: "damit, dieselben Nachrichten zu beantworten und Leads nachzuverfolgen.",
    trust_p2: "Wir bauen KI-Systeme, die das automatisch erledigen — schnell, professionell und fehlerfrei.",
    trust_p2b: "und Sie bekommen Ihre Zeit zurück.",
    trust_p3: "Wir verkaufen keine komplizierte Technologie. Wir verkaufen Zeit, Effizienz und Seelenfrieden.",
    tc1_title: "Keine technischen Kenntnisse nötig", tc1_desc: "Wir kümmern uns um alles, Sie prüfen nur die Ergebnisse.",
    tc2_title: "Integration mit Ihren Tools", tc2_desc: "Gmail, WhatsApp, Calendly, CRM — wir verbinden alles.",
    tc3_title: "KI, die wie Sie spricht", tc3_desc: "Antworten sind auf den Ton Ihrer Marke abgestimmt.",
    tc4_title: "Support nach der Umsetzung", tc4_desc: "Wir verschwinden nicht. Wir optimieren kontinuierlich für Sie.",
    contact_tagline: "Lassen Sie die Automatisierung\nfür Sie arbeiten",
    contact_whatsapp: "WhatsApp",
    footer_rights: "Alle Rechte vorbehalten.",
    footer_privacy: "Datenschutzrichtlinie",
    footer_terms: "Allgemeine Geschäftsbedingungen",
    cp_title: "Lassen Sie uns",
    cp_title2: "Ihr Unternehmen automatisieren",
    cp_note: "Durch Drücken des Buttons werden Sie zu WhatsApp weitergeleitet.",
    cp_back_label: "Zurück",
    cp_inquiry_type: "Art der Anfrage",
    cp_select: "Option auswählen",
    cp_about: "Über Sie",
    cp_firstname: "Vorname",
    cp_lastname: "Nachname",
    cp_email: "E-Mail",
    cp_phone: "Telefon",
    cp_business: "Art des Unternehmens",
    cp_message: "Was möchten Sie automatisieren?",
    cp_submit: "Per WhatsApp senden",
  },
  fr: {
    nav_automations: "Automatisations",
    nav_services: "Services",
    services_btn: "Ce Que Nous Automatisons Pour Vous",
    nav_how: "Comment ça marche",
    nav_about: "À propos",
    nav_contact: "Contact",
    hero_sub: "AUTOMATISATIONS IA.",
    hero_desc: "Fini le travail répétitif. Nous répondons automatiquement aux e-mails, messages, rendez-vous et plus — avec l'IA.",
    hero_cta1: "Consultation gratuite",
    hero_cta2: "Voir comment ça marche",
    hero_tag1: "⚡ Déploiement en 7 jours garanti",
    hero_tag2: "🤖 Réponses IA 24h/24",
    hero_tag3: "🔒 Sans frais cachés",
    benefits_title: "Tout ce dont vous avez besoin pour",
    benefits_title2: "automatiser votre entreprise",
    b1_title: "Réponses automatiques aux messages",
    b1_desc: "Notre IA répond instantanément aux e-mails, WhatsApp et DMs — sans que vous ayez à lever le petit doigt.",
    b2_title: "Gestion automatique des rendez-vous",
    b2_desc: "Les clients prennent rendez-vous eux-mêmes, reçoivent des confirmations et rappels.",
    b3_title: "Économisez des dizaines d'heures par mois",
    b3_desc: "Votre équipe se concentre sur l'essentiel, pas sur les tâches répétitives.",
    b4_title: "Disponible 24h/24, sans interruption",
    b4_desc: "Les automatisations tournent en continu. Les clients reçoivent une réponse même la nuit.",
    b5_title: "Intégration rapide et simple",
    b5_desc: "Inutile de changer quoi que ce soit. Nous intégrons l'IA dans les outils que vous utilisez déjà.",
    b6_title: "Résultats mesurables immédiatement",
    b6_desc: "Voyez en temps réel combien de messages, rendez-vous et leads sont gérés automatiquement.",
    services_title: "Qu'est-ce que nous automatisons",
    services_title2: "pour vous ?",
    services_sub: "Quel que soit votre type d'entreprise, nous avons l'automatisation adaptée.",
    s1_tag: "Communication", s1_title: "Réponses automatiques IA",
    s1_desc: "Un assistant IA qui répond aux e-mails, messages WhatsApp, DMs Instagram — instantanément, 24h/24.",
    s1_f1: "Réponses e-mail automatiques", s1_f2: "WhatsApp & Instagram DM", s1_f3: "Ton personnalisé à la marque", s1_f4: "Escalade intelligente",
    s2_tag: "Rendez-vous", s2_title: "Gestion automatique des rendez-vous",
    s2_desc: "Les clients réservent en ligne, reçoivent des confirmations automatiques et des rappels.",
    s2_f1: "Calendrier intégré automatiquement", s2_f2: "Confirmations & rappels SMS/e-mail", s2_f3: "Reports sans intervention", s2_f4: "Synchronisation Google Agenda",
    s3_tag: "Leads", s3_title: "Capture & nurturing de leads",
    s3_desc: "L'IA identifie les clients potentiels, leur répond immédiatement et les guide vers la conversion.",
    s3_f1: "Réponse instantanée aux nouveaux leads", s3_f2: "Suivi automatisé", s3_f3: "Qualification des leads par IA", s3_f4: "Intégration CRM",
    services_cta: "Demander un devis",
    sv1_title: "Qualification & prospection de leads IA",
    sv2_title: "Chatbot IA pour le support client",
    sv3_title: "Pipeline de contenu pour les réseaux sociaux",
    sv4_title: "Traitement des factures & documents",
    sv5_title: "Enrichissement & synchronisation des données CRM",
    sv6_title: "Automatisation des rendez-vous & réservations",
    sv7_title: "Rapports & analyses IA",
    sv8_title: "Surveillance & réponse aux avis",
    sv9_title: "Gestion des commandes & stocks e-commerce",
    sv10_title: "Workflow d'onboarding des employés",
    sv11_title: "Automatisation personnalisée",
    how_title: "3 étapes simples vers",
    how_title2: "votre entreprise automatisée",
    how_sub: "Notre processus est simple et transparent. Vous êtes informé à chaque étape.",
    step1_title: "Contactez-nous", step1_desc: "Envoyez un message ou remplissez le formulaire. Nous analysons gratuitement vos processus répétitifs.",
    step2_title: "Nous concevons l'automatisation", step2_desc: "Nous construisons des workflows IA personnalisés — intégrés aux outils que vous utilisez déjà.",
    step3_title: "L'IA travaille pour vous", step3_desc: "En 7 jours, les automatisations sont en ligne. Les clients reçoivent des réponses instantanées.",
    how_cta: "Commencer maintenant — consultation gratuite",
    trust_title: "Nous automatisons les entreprises qui veulent",
    trust_title2: "croître sans travailler davantage",
    trust_p1: "Valaro est né d'un vrai problème :",
    trust_p1b: "les entrepreneurs perdent des heures chaque jour",
    trust_p1c: "à répondre aux mêmes messages, gérer des rendez-vous et suivre des leads.",
    trust_p2: "Nous construisons des systèmes IA qui font cela automatiquement — vite, professionnellement.",
    trust_p2b: "et vous récupérez votre temps.",
    trust_p3: "Nous ne vendons pas de technologie compliquée. Nous vendons du temps, de l'efficacité et la tranquillité.",
    tc1_title: "Aucune compétence technique requise", tc1_desc: "Nous gérons tout, vous vérifiez simplement les résultats.",
    tc2_title: "Intégration avec vos outils", tc2_desc: "Gmail, WhatsApp, Calendly, CRM — nous connectons tout.",
    tc3_title: "Une IA qui parle comme vous", tc3_desc: "Les réponses sont personnalisées selon le ton de votre marque.",
    tc4_title: "Support après déploiement", tc4_desc: "Nous ne disparaissons pas. Nous optimisons en continu pour vous.",
    contact_tagline: "Laissez l'automatisation\ntravailler pour vous",
    contact_whatsapp: "WhatsApp",
    footer_rights: "Tous droits réservés.",
    footer_privacy: "Politique de confidentialité",
    footer_terms: "Conditions d'utilisation",
    cp_title: "Automatisons",
    cp_title2: "votre entreprise",
    cp_note: "En appuyant sur le bouton, vous serez redirigé vers WhatsApp avec le message complété.",
    cp_back_label: "Retour",
    cp_inquiry_type: "Type de demande",
    cp_select: "Sélectionnez une option",
    cp_about: "À votre sujet",
    cp_firstname: "Prénom",
    cp_lastname: "Nom",
    cp_email: "E-mail",
    cp_phone: "Téléphone",
    cp_business: "Type d'entreprise",
    cp_message: "Que souhaitez-vous automatiser ?",
    cp_submit: "Envoyer via WhatsApp",
  },
};

const LanguageContext = createContext({ lang: "ro", t: translations.ro, setLang: () => {} });

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState("ro");
  const t = translations[lang];
  return (
    <LanguageContext.Provider value={{ lang, t, setLang }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLang() {
  return useContext(LanguageContext);
}
